name: temp
description: Proyecto final de Flutter Pokedex Interactivo.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.1
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.1
  shared_preferences: ^2.2.2
  sliding_up_panel2: ^3.3.0+1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/icons/
    - assets/images/pokemons/
    - assets/images/types/
    - assets/images/utils/
    - assets/images/backgrounds/
    - assets/images/stats/

  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Black.ttf
        - asset: assets/fonts/Inconsolata-Bold.ttf
        - asset: assets/fonts/Inconsolata-ExtraBold.ttf
        - asset: assets/fonts/Inconsolata-Medium.ttf
        - asset: assets/fonts/Inconsolata-Regular.ttf
        - asset: assets/fonts/Inconsolata-SemiBold.ttf
    - family: Ligconsolata
      fonts:
        - asset: assets/fonts/Ligconsolata-Bold.ttf
        - asset: assets/fonts/Ligconsolata-Regular.ttf

  uses-material-design: true

